--- 
abstract: Generates constants at runtime
author: Anders Nor Berle <debolaz@gmail.com>
build_requires: 
  Test::More: 0.47
  Test::Pod: 1.26
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Constant-Runtime
no_index: 
  directory: 
    - inc
    - t
version: 0.01
